#!/usr/bin/env bash
# 0-world_wide_web --script to display info about subdomains

# show_dom() function
show_dom() {
if [ "$2" ];
then
    echo -n "The subdomain $2 is a"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to "$5}' | tail -n 1
else
    for subdom in www lb-01 web-01 web-02 
    do
        echo -n "The subdomain $subdom is a"
        dig "$subdom.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to "$5}' | tail -n 1
    done
fi
}
show_dom "$1" "$2"
