#!/usr/bin/env bash
# configure my Nginx server so that /redirect_me is redirecting
# to another page.
apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
 sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/Yosinan/ permanent;" /etc/nginx/sites-enabled/default

service nginx restart
