#!/usr/bin/env bash
# a bash script that installs nginx webserver

apt-get -y update &&  apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "301 Moved Permanently" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
