#!/usr/bin/env bash                                                           
# this script will install and configure HAproxy on my lb-01 server                          
apt-get update -y
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*

# this will edit the init script at /etc/default/haproxy and setting ENABLED to 1

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# if we wld like to archieve or keep the old config file we can move ot to new file
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.previous

# now we start to configure the file
{
echo -e "\
frontend fproxy
\tbind *:80
\tmode http
\tdefault_backend my_backend

backend bproxy
\tbalance roundrobin
\tserver 118467-web-01 18.235.248.166:80 check
\tserver 118467-web-02 100.26.226.17:80 check"
} | sudo tee -a /etc/haproxy/haproxy.cfg

# restarting the proxy
sudo service haproxy restart
