#!/usr/bin/env bash
# a script to Install and configure HAproxy on lb-01 server

sudo apt-get update -y
sudo apt-get install haproxy -y

confi=\
"
backend web-backend
	balance roundrobin
	server 118467-web-01 18.235.248.166:80 check
	server 118467-web-02 100.26.226.17:80 check
	mode http
frontend http
	bind *:80
	mode http
	default_backend web-backend
"

echo "$confi" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
