#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

confi=\
"
backend app
        balance roundrobin
        server 118467-web-01 18.235.248.166:80 check
        server 118467-web-02 100.26.226.17:80 check
frontend alifcodeweb
        bind *:80
        mode http
        default_backend app
"
echo "$confi" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
