#!/usr/bin/env bash
# a script to generate a MySQL dump and creates a compressed archive from it

# variables for user, date and password
pass=$1
usr="root"
arch_name=$(date +"%d-%m-%Y").tar.gz

# creating mysql dump
sudo mysqldump --all-databases -u$usr -p"$pass" > backup.sqli

# compressing it to archieved file
sudo tar -czvf "$arch_name" backup.sql
