#!/usr/bin/env bash
#nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
