#!/usr/bin/env bash
# nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
# a Bash script that configures a server to the above requirements
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
