#!/usr/bin/env bash
# script to Block all incoming traffic but SSH, HTTPS SSL, HTTP and allow all outgoing traffic
sudo apt-get update
sudo apt-get install ufw

sudo ufw disable
# allowing all outgoing traffic
sudo ufw default allow outgoing

# denying all incoming traffic
sudo ufw default deny incoming

# allow only HTTPS, SSH and HTTP incoming traffic
sudo ufw allow ssh/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp

# enabling ufw
sudo ufw enable 
