#!/usr/bin/env bash
#  task #1, makemy prev fix short and sweet
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
