#!/usr/bin/env bash
# client configuration file - to refuse authentication using passwword
Host default
  HostName 34.227.101.45
  User ubuntu
  Port 22
  PasswordAuthentication no
  IdentityFile ~/.ssh/school
